import numpy as np
import matplotlib.pyplot as plt

mse_pde_1 = np.load('logs/MSE_PDE_1.npy')
mse_pde_2 = np.load('logs/MSE_PDE_2.npy')
mse_pde_3 = np.load('logs/MSE_PDE_3.npy')
mse_obs_1 = np.load('logs/MSE_OBS_1.npy')
mse_obs_2 = np.load('logs/MSE_OBS_2.npy')
sigma1 = np.load('logs/Sigma1.npy')
sigma2 = np.load('logs/Sigma2.npy')
sigma3 = np.load('logs/Sigma3.npy')
sigma4 = np.load('logs/Sigma4.npy')
sigma5 = np.load('logs/Sigma5.npy')

fig, axs = plt.subplots(2, 3, figsize=(12, 8))
axs[0, 0].plot(mse_pde_1)
axs[0, 0].set_title('MSE_PDE_1')
axs[0, 1].plot(mse_pde_2)
axs[0, 1].set_title('MSE_PDE_2')
axs[0, 2].plot(mse_pde_3)
axs[0, 2].set_title('MSE_PDE_3')
axs[1, 0].plot(mse_obs_1)
axs[1, 0].set_title('MSE_OBS_1')
axs[1, 1].plot(mse_obs_2)
axs[1, 1].set_title('MSE_OBS_2')
axs[1, 2].plot(sigma1)
axs[1, 2].set_title('Sigma1')
axs[1, 2].plot(sigma2)
axs[1, 2].set_title('Sigma2')
axs[1, 2].plot(sigma3)
axs[1, 2].set_title('Sigma3')
axs[1, 2].plot(sigma4)
axs[1, 2].set_title('Sigma4')
axs[1, 2].plot(sigma5)
axs[1, 2].set_title('Sigma5')
plt.show()
